USE ContosoRetailDW;

-- PERCENTUAL RECEITA (CANAL FÍSICO X CANAL ONLINE)

WITH ANALISE_1
AS (

SELECT 
'Canal Físico' AS CANAL,
CAST(SUM(F.SalesAmount) AS DECIMAL(18,4)) AS RECEITA
FROM FactSales AS F

UNION ALL

SELECT 
'Canal Online' AS CANAL,
CAST(SUM(FA.SalesAmount) AS DECIMAL(18,4)) AS RECEITA
FROM FactOnlineSales AS FA
)

SELECT 
CANAL,
RECEITA,
SUM(RECEITA) OVER () AS RECEITA_TOTAL,
ROUND(RECEITA * 100.0 / SUM(RECEITA) OVER (), 2) AS PERCENTUAL
FROM ANALISE_1